# Generated by Django 4.1.7 on 2023-03-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
